//! Content hashes (MD5 / SHA-1 / SHA-256 / BLAKE3 / CRC32) and hash-file verify.

use std::fmt;
use std::fmt::Write as _;

use digest::Digest;
use tokio::io::AsyncReadExt;

use crate::error::{FsError, Result};
use crate::path::FsPath;
use crate::provider::FsProviderRegistry;

/// Supported digest algorithms.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HashAlgo {
    /// MD5 (128-bit). Weak; kept for compatibility with `.md5` sidecars.
    Md5,
    /// SHA-1 (160-bit). Weak; kept for `.sha1` sidecars.
    Sha1,
    /// SHA-256.
    Sha256,
    /// BLAKE3 (256-bit).
    Blake3,
    /// CRC-32 (IEEE), typically stored as `.sfv`.
    Crc32,
}

impl HashAlgo {
    /// Stable lowercase name (`"sha256"`).
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Md5 => "md5",
            Self::Sha1 => "sha1",
            Self::Sha256 => "sha256",
            Self::Blake3 => "blake3",
            Self::Crc32 => "crc32",
        }
    }

    /// Sidecar extension without the dot.
    #[must_use]
    pub fn ext(self) -> &'static str {
        match self {
            Self::Crc32 => "sfv",
            other => other.as_str(),
        }
    }

    /// Parse from a name or file extension.
    #[must_use]
    pub fn from_name(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "md5" | "md5sum" => Some(Self::Md5),
            "sha1" | "sha-1" | "sha1sum" => Some(Self::Sha1),
            "sha256" | "sha-256" | "sha256sum" => Some(Self::Sha256),
            "blake3" | "b3" => Some(Self::Blake3),
            "crc32" | "sfv" => Some(Self::Crc32),
            _ => None,
        }
    }
}

impl fmt::Display for HashAlgo {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// One hashed file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HashRecord {
    /// Path that was hashed.
    pub path: FsPath,
    /// Display name (file name or relative path).
    pub name: String,
    /// Lowercase hex digest (CRC-32 is 8 hex chars).
    pub hex: String,
}

/// Hash `path` with `algo` by streaming through the provider.
///
/// # Errors
///
/// Propagates provider / I/O errors.
pub async fn hash_path(
    registry: &FsProviderRegistry,
    path: &FsPath,
    algo: HashAlgo,
) -> Result<HashRecord> {
    let provider = registry
        .for_path(path)
        .ok_or_else(|| FsError::ProviderNotMounted(path.to_string()))?;
    let mut reader = provider.read_stream(path).await?;
    let hex = hash_reader(&mut reader, algo).await?;
    let name = path.file_name().unwrap_or(path.as_str()).to_string();
    Ok(HashRecord {
        path: path.clone(),
        name,
        hex,
    })
}

/// Hash several paths; directories are skipped.
///
/// # Errors
///
/// First provider / I/O error stops the batch.
pub async fn hash_paths(
    registry: &FsProviderRegistry,
    paths: &[FsPath],
    algo: HashAlgo,
) -> Result<Vec<HashRecord>> {
    let mut out = Vec::new();
    for p in paths {
        let provider = registry
            .for_path(p)
            .ok_or_else(|| FsError::ProviderNotMounted(p.to_string()))?;
        let meta = provider.metadata(p).await?;
        if matches!(meta.kind, crate::entry::FsEntryKind::Directory) {
            continue;
        }
        out.push(hash_path(registry, p, algo).await?);
    }
    Ok(out)
}

/// Write `records` next to `dest` in GNU coreutils / SFV form.
///
/// # Errors
///
/// I/O errors from the provider write.
pub async fn write_hash_file(
    registry: &FsProviderRegistry,
    dest: &FsPath,
    algo: HashAlgo,
    records: &[HashRecord],
) -> Result<()> {
    let provider = registry
        .for_path(dest)
        .ok_or_else(|| FsError::ProviderNotMounted(dest.to_string()))?;
    let mut body = String::new();
    if algo == HashAlgo::Crc32 {
        body.push_str("; generated by Orchid\r\n");
        for r in records {
            body.push_str(&format!("{} {}\r\n", r.name, r.hex.to_ascii_uppercase()));
        }
    } else {
        for r in records {
            body.push_str(&format!("{} *{}\n", r.hex, r.name));
        }
    }
    provider.write(dest, body.as_bytes()).await
}

/// One row from a checksum sidecar.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifyRow {
    /// File name as stored in the sidecar (not a full path).
    pub name: String,
    /// Expected hex digest.
    pub expected: String,
    /// Actual digest when the file was found.
    pub actual: Option<String>,
    /// Whether the file matched.
    pub ok: bool,
    /// Missing on disk.
    pub missing: bool,
}

/// Parse a checksum / SFV file and verify sibling files.
///
/// # Errors
///
/// Propagates read errors for the sidecar; missing payload files are reported
/// as rows, not errors.
pub async fn verify_hash_file(
    registry: &FsProviderRegistry,
    sidecar: &FsPath,
) -> Result<Vec<VerifyRow>> {
    let provider = registry
        .for_path(sidecar)
        .ok_or_else(|| FsError::ProviderNotMounted(sidecar.to_string()))?;
    let bytes = provider.read(sidecar).await?;
    let text = String::from_utf8_lossy(&bytes);
    let algo = sidecar
        .extension()
        .and_then(HashAlgo::from_name)
        .or_else(|| detect_algo_from_body(&text))
        .unwrap_or(HashAlgo::Sha256);
    let parent = sidecar.parent().ok_or_else(|| FsError::InvalidPath {
        reason: "hash file has no parent".into(),
    })?;
    let mut rows = Vec::new();
    for (name, expected) in parse_hash_body(&text, algo) {
        let file = parent.join(&name);
        let exists = registry
            .for_path(&file)
            .ok_or_else(|| FsError::ProviderNotMounted(file.to_string()))?
            .exists(&file)
            .await
            .unwrap_or(false);
        if !exists {
            rows.push(VerifyRow {
                name,
                expected,
                actual: None,
                ok: false,
                missing: true,
            });
            continue;
        }
        let rec = hash_path(registry, &file, algo).await?;
        let ok = rec.hex.eq_ignore_ascii_case(&expected);
        rows.push(VerifyRow {
            name,
            expected,
            actual: Some(rec.hex),
            ok,
            missing: false,
        });
    }
    Ok(rows)
}

async fn hash_reader(
    reader: &mut (dyn tokio::io::AsyncRead + Unpin + Send),
    algo: HashAlgo,
) -> Result<String> {
    let mut buf = vec![0u8; 1024 * 1024];
    match algo {
        HashAlgo::Md5 => {
            let mut h = md5::Md5::new();
            pump(reader, &mut buf, |c| h.update(c)).await?;
            Ok(hex::encode(h.finalize()))
        }
        HashAlgo::Sha1 => {
            let mut h = sha1::Sha1::new();
            pump(reader, &mut buf, |c| h.update(c)).await?;
            Ok(hex::encode(h.finalize()))
        }
        HashAlgo::Sha256 => {
            let mut h = sha2::Sha256::new();
            pump(reader, &mut buf, |c| h.update(c)).await?;
            Ok(hex::encode(h.finalize()))
        }
        HashAlgo::Blake3 => {
            let mut h = blake3::Hasher::new();
            pump(reader, &mut buf, |c| {
                h.update(c);
            })
            .await?;
            Ok(hex::encode(h.finalize().as_bytes()))
        }
        HashAlgo::Crc32 => {
            let mut h = crc32fast::Hasher::new();
            pump(reader, &mut buf, |c| h.update(c)).await?;
            Ok(format!("{:08x}", h.finalize()))
        }
    }
}

async fn pump(
    reader: &mut (dyn tokio::io::AsyncRead + Unpin + Send),
    buf: &mut [u8],
    mut update: impl FnMut(&[u8]),
) -> Result<()> {
    loop {
        let n = reader.read(buf).await?;
        if n == 0 {
            break;
        }
        update(&buf[..n]);
    }
    Ok(())
}

fn detect_algo_from_body(text: &str) -> Option<HashAlgo> {
    for line in text.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with(';') || t.starts_with('#') {
            continue;
        }
        if let Some((hash, _)) = split_hash_line(t) {
            return match hash.len() {
                8 => Some(HashAlgo::Crc32),
                32 => Some(HashAlgo::Md5),
                40 => Some(HashAlgo::Sha1),
                64 => Some(HashAlgo::Sha256),
                _ => None,
            };
        }
    }
    None
}

fn parse_hash_body(text: &str, algo: HashAlgo) -> Vec<(String, String)> {
    let mut rows = Vec::new();
    for line in text.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with(';') || t.starts_with('#') {
            continue;
        }
        if algo == HashAlgo::Crc32 {
            // `name CRC32` — CRC is last token.
            if let Some((name, crc)) = t.rsplit_once(char::is_whitespace) {
                if crc.len() == 8 && crc.chars().all(|c| c.is_ascii_hexdigit()) {
                    rows.push((name.trim().to_string(), crc.to_ascii_lowercase()));
                    continue;
                }
            }
        }
        if let Some((hash, name)) = split_hash_line(t) {
            rows.push((name, hash.to_ascii_lowercase()));
        }
    }
    rows
}

fn split_hash_line(t: &str) -> Option<(&str, String)> {
    let (hash, rest) = t.split_once(char::is_whitespace)?;
    if !hash.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    if !matches!(hash.len(), 8 | 32 | 40 | 64) {
        return None;
    }
    let name = rest
        .trim()
        .trim_start_matches('*')
        .trim()
        .replace('\\', "/");
    if name.is_empty() {
        return None;
    }
    Some((hash, name))
}

/// Format records as a human-readable report.
#[must_use]
pub fn format_hash_report(algo: HashAlgo, records: &[HashRecord]) -> String {
    let mut s = String::new();
    let _ = writeln!(&mut s, "{}", algo.as_str());
    for r in records {
        let _ = writeln!(&mut s, "{}  {}", r.hex, r.name);
    }
    s
}

/// Format verify rows as a human-readable report.
#[must_use]
pub fn format_verify_report(rows: &[VerifyRow]) -> String {
    let mut ok = 0usize;
    let mut bad = 0usize;
    let mut missing = 0usize;
    let mut s = String::new();
    for r in rows {
        if r.missing {
            missing += 1;
            let _ = writeln!(&mut s, "MISSING  {}", r.name);
        } else if r.ok {
            ok += 1;
            let _ = writeln!(&mut s, "OK       {}", r.name);
        } else {
            bad += 1;
            let _ = writeln!(
                &mut s,
                "FAIL     {}  expected {} got {}",
                r.name,
                r.expected,
                r.actual.as_deref().unwrap_or("-")
            );
        }
    }
    let _ = writeln!(
        &mut s,
        "\n{ok} ok, {bad} failed, {missing} missing ({total} files)",
        total = rows.len()
    );
    s
}

/// Guess whether `path` looks like a checksum sidecar.
#[must_use]
pub fn is_hash_sidecar(path: &FsPath) -> bool {
    path.extension()
        .is_some_and(|e| HashAlgo::from_name(e).is_some() || e.eq_ignore_ascii_case("md5sum"))
}

/// Used by unit tests to hash an on-disk file without a registry.
#[cfg(test)]
pub(crate) fn hash_local_file_for_test(path: &std::path::Path, algo: HashAlgo) -> String {
    let data = std::fs::read(path).expect("read");
    match algo {
        HashAlgo::Md5 => hex::encode(md5::Md5::digest(&data)),
        HashAlgo::Sha1 => hex::encode(sha1::Sha1::digest(&data)),
        HashAlgo::Sha256 => hex::encode(sha2::Sha256::digest(&data)),
        HashAlgo::Blake3 => hex::encode(blake3::hash(&data).as_bytes()),
        HashAlgo::Crc32 => format!("{:08x}", crc32fast::hash(&data)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_gnu_and_sfv() {
        let gnu = "d41d8cd98f00b204e9800998ecf8427e *empty.txt\n";
        let rows = parse_hash_body(gnu, HashAlgo::Md5);
        assert_eq!(rows[0].0, "empty.txt");
        assert_eq!(rows[0].1.len(), 32);

        let sfv = "; comment\r\nfile.bin AABBCCDD\r\n";
        let rows = parse_hash_body(sfv, HashAlgo::Crc32);
        assert_eq!(rows[0].0, "file.bin");
        assert_eq!(rows[0].1, "aabbccdd");
    }

    #[test]
    fn local_hash_known() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("a.bin");
        std::fs::write(&p, b"abc").unwrap();
        assert_eq!(
            hash_local_file_for_test(&p, HashAlgo::Md5),
            "900150983cd24fb0d6963f7d28e17f72"
        );
        assert_eq!(
            hash_local_file_for_test(&p, HashAlgo::Sha256),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
    }
}
