// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod orchid {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod format {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_REGION_TYPE: u16 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_REGION_TYPE: u16 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_REGION_TYPE: [RegionType; 6] = [
  RegionType::Raw,
  RegionType::CleanText,
  RegionType::Structured,
  RegionType::Embedding,
  RegionType::Provenance,
  RegionType::VersionHistory,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct RegionType(pub u16);
#[allow(non_upper_case_globals)]
impl RegionType {
  pub const Raw: Self = Self(1);
  pub const CleanText: Self = Self(2);
  pub const Structured: Self = Self(3);
  pub const Embedding: Self = Self(4);
  pub const Provenance: Self = Self(5);
  pub const VersionHistory: Self = Self(6);

  pub const ENUM_MIN: u16 = 1;
  pub const ENUM_MAX: u16 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Raw,
    Self::CleanText,
    Self::Structured,
    Self::Embedding,
    Self::Provenance,
    Self::VersionHistory,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Raw => Some("Raw"),
      Self::CleanText => Some("CleanText"),
      Self::Structured => Some("Structured"),
      Self::Embedding => Some("Embedding"),
      Self::Provenance => Some("Provenance"),
      Self::VersionHistory => Some("VersionHistory"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for RegionType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for RegionType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u16>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for RegionType {
    type Output = RegionType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u16>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for RegionType {
  type Scalar = u16;
  #[inline]
  fn to_little_endian(self) -> u16 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u16) -> Self {
    let b = u16::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for RegionType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u16::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for RegionType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_COMPRESSION_CODEC: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_COMPRESSION_CODEC: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_COMPRESSION_CODEC: [CompressionCodec; 2] = [
  CompressionCodec::None,
  CompressionCodec::Zstd,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct CompressionCodec(pub u8);
#[allow(non_upper_case_globals)]
impl CompressionCodec {
  pub const None: Self = Self(0);
  pub const Zstd: Self = Self(1);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Zstd,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Zstd => Some("Zstd"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for CompressionCodec {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for CompressionCodec {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for CompressionCodec {
    type Output = CompressionCodec;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for CompressionCodec {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for CompressionCodec {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for CompressionCodec {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_STORAGE_MODE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_STORAGE_MODE: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_STORAGE_MODE: [StorageMode; 2] = [
  StorageMode::Inline,
  StorageMode::Linked,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct StorageMode(pub u8);
#[allow(non_upper_case_globals)]
impl StorageMode {
  pub const Inline: Self = Self(0);
  pub const Linked: Self = Self(1);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Inline,
    Self::Linked,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Inline => Some("Inline"),
      Self::Linked => Some("Linked"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for StorageMode {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for StorageMode {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for StorageMode {
    type Output = StorageMode;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for StorageMode {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for StorageMode {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for StorageMode {}
pub enum EncryptionInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EncryptionInfo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EncryptionInfo<'a> {
  type Inner = EncryptionInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EncryptionInfo<'a> {
  pub const VT_AGE_HEADER: flatbuffers::VOffsetT = 4;
  pub const VT_PLAINTEXT_BLAKE3: flatbuffers::VOffsetT = 6;
  pub const VT_IDENTITY_KIND: flatbuffers::VOffsetT = 8;
  pub const VT_IS_PUBLIC: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EncryptionInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EncryptionInfoArgs<'args>
  ) -> flatbuffers::WIPOffset<EncryptionInfo<'bldr>> {
    let mut builder = EncryptionInfoBuilder::new(_fbb);
    if let Some(x) = args.plaintext_blake3 { builder.add_plaintext_blake3(x); }
    if let Some(x) = args.age_header { builder.add_age_header(x); }
    builder.add_is_public(args.is_public);
    builder.add_identity_kind(args.identity_kind);
    builder.finish()
  }


  /// age recipient stanzas or opaque age header prefix length.
  #[inline]
  pub fn age_header(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(EncryptionInfo::VT_AGE_HEADER, None)}
  }
  /// BLAKE3-256 of the plaintext (after decompress).
  #[inline]
  pub fn plaintext_blake3(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(EncryptionInfo::VT_PLAINTEXT_BLAKE3, None)}
  }
  /// Identity kind hint: 0 = passphrase, 1 = x25519 (mirrors IdentityKind).
  #[inline]
  pub fn identity_kind(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(EncryptionInfo::VT_IDENTITY_KIND, Some(0)).unwrap()}
  }
  /// True if this region is classified public (may still be integrity-hashed).
  #[inline]
  pub fn is_public(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(EncryptionInfo::VT_IS_PUBLIC, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for EncryptionInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("age_header", Self::VT_AGE_HEADER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("plaintext_blake3", Self::VT_PLAINTEXT_BLAKE3, false)?
     .visit_field::<u8>("identity_kind", Self::VT_IDENTITY_KIND, false)?
     .visit_field::<bool>("is_public", Self::VT_IS_PUBLIC, false)?
     .finish();
    Ok(())
  }
}
pub struct EncryptionInfoArgs<'a> {
    pub age_header: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub plaintext_blake3: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub identity_kind: u8,
    pub is_public: bool,
}
impl<'a> Default for EncryptionInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    EncryptionInfoArgs {
      age_header: None,
      plaintext_blake3: None,
      identity_kind: 0,
      is_public: false,
    }
  }
}

pub struct EncryptionInfoBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EncryptionInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_age_header(&mut self, age_header: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EncryptionInfo::VT_AGE_HEADER, age_header);
  }
  #[inline]
  pub fn add_plaintext_blake3(&mut self, plaintext_blake3: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EncryptionInfo::VT_PLAINTEXT_BLAKE3, plaintext_blake3);
  }
  #[inline]
  pub fn add_identity_kind(&mut self, identity_kind: u8) {
    self.fbb_.push_slot::<u8>(EncryptionInfo::VT_IDENTITY_KIND, identity_kind, 0);
  }
  #[inline]
  pub fn add_is_public(&mut self, is_public: bool) {
    self.fbb_.push_slot::<bool>(EncryptionInfo::VT_IS_PUBLIC, is_public, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EncryptionInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EncryptionInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EncryptionInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EncryptionInfo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EncryptionInfo");
      ds.field("age_header", &self.age_header());
      ds.field("plaintext_blake3", &self.plaintext_blake3());
      ds.field("identity_kind", &self.identity_kind());
      ds.field("is_public", &self.is_public());
      ds.finish()
  }
}
pub enum ChunkRefOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChunkRef<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ChunkRef<'a> {
  type Inner = ChunkRef<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ChunkRef<'a> {
  pub const VT_BLAKE3: flatbuffers::VOffsetT = 4;
  pub const VT_SIZE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ChunkRef { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ChunkRefArgs<'args>
  ) -> flatbuffers::WIPOffset<ChunkRef<'bldr>> {
    let mut builder = ChunkRefBuilder::new(_fbb);
    builder.add_size(args.size);
    if let Some(x) = args.blake3 { builder.add_blake3(x); }
    builder.finish()
  }


  #[inline]
  pub fn blake3(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(ChunkRef::VT_BLAKE3, None)}
  }
  #[inline]
  pub fn size(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ChunkRef::VT_SIZE, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ChunkRef<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("blake3", Self::VT_BLAKE3, false)?
     .visit_field::<u64>("size", Self::VT_SIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct ChunkRefArgs<'a> {
    pub blake3: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub size: u64,
}
impl<'a> Default for ChunkRefArgs<'a> {
  #[inline]
  fn default() -> Self {
    ChunkRefArgs {
      blake3: None,
      size: 0,
    }
  }
}

pub struct ChunkRefBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ChunkRefBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_blake3(&mut self, blake3: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChunkRef::VT_BLAKE3, blake3);
  }
  #[inline]
  pub fn add_size(&mut self, size: u64) {
    self.fbb_.push_slot::<u64>(ChunkRef::VT_SIZE, size, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ChunkRefBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ChunkRefBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ChunkRef<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ChunkRef<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ChunkRef");
      ds.field("blake3", &self.blake3());
      ds.field("size", &self.size());
      ds.finish()
  }
}
pub enum RegionEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RegionEntry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RegionEntry<'a> {
  type Inner = RegionEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RegionEntry<'a> {
  pub const VT_TYPE_: flatbuffers::VOffsetT = 4;
  pub const VT_OFFSET: flatbuffers::VOffsetT = 6;
  pub const VT_LENGTH: flatbuffers::VOffsetT = 8;
  pub const VT_NAME: flatbuffers::VOffsetT = 10;
  pub const VT_ORDINAL: flatbuffers::VOffsetT = 12;
  pub const VT_COMPRESSION: flatbuffers::VOffsetT = 14;
  pub const VT_STORAGE: flatbuffers::VOffsetT = 16;
  pub const VT_CHUNKS: flatbuffers::VOffsetT = 18;
  pub const VT_ENCRYPTION: flatbuffers::VOffsetT = 20;
  pub const VT_CONTENT_TYPE: flatbuffers::VOffsetT = 22;
  pub const VT_PAYLOAD_BLAKE3: flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RegionEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RegionEntryArgs<'args>
  ) -> flatbuffers::WIPOffset<RegionEntry<'bldr>> {
    let mut builder = RegionEntryBuilder::new(_fbb);
    builder.add_length(args.length);
    builder.add_offset(args.offset);
    if let Some(x) = args.payload_blake3 { builder.add_payload_blake3(x); }
    if let Some(x) = args.content_type { builder.add_content_type(x); }
    if let Some(x) = args.encryption { builder.add_encryption(x); }
    if let Some(x) = args.chunks { builder.add_chunks(x); }
    builder.add_ordinal(args.ordinal);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_type_(args.type_);
    builder.add_storage(args.storage);
    builder.add_compression(args.compression);
    builder.finish()
  }


  /// Defaults to Raw so FlatBuffers' zero-init stays in-enum (ids start at 1).
  #[inline]
  pub fn type_(&self) -> RegionType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RegionType>(RegionEntry::VT_TYPE_, Some(RegionType::Raw)).unwrap()}
  }
  /// Absolute file offset of local_magic ORCR.
  #[inline]
  pub fn offset(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RegionEntry::VT_OFFSET, Some(0)).unwrap()}
  }
  /// Length field from mini-header (enc_meta || payload).
  #[inline]
  pub fn length(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RegionEntry::VT_LENGTH, Some(0)).unwrap()}
  }
  /// Human name (e.g. relative path for FM wrap).
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RegionEntry::VT_NAME, None)}
  }
  /// Stable order among siblings of the same type.
  #[inline]
  pub fn ordinal(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(RegionEntry::VT_ORDINAL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn compression(&self) -> CompressionCodec {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<CompressionCodec>(RegionEntry::VT_COMPRESSION, Some(CompressionCodec::None)).unwrap()}
  }
  #[inline]
  pub fn storage(&self) -> StorageMode {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<StorageMode>(RegionEntry::VT_STORAGE, Some(StorageMode::Inline)).unwrap()}
  }
  /// Inline: empty. Linked: ordered FastCDC chunk hashes.
  #[inline]
  pub fn chunks(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChunkRef<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChunkRef>>>>(RegionEntry::VT_CHUNKS, None)}
  }
  #[inline]
  pub fn encryption(&self) -> Option<EncryptionInfo<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<EncryptionInfo>>(RegionEntry::VT_ENCRYPTION, None)}
  }
  /// MIME or model id / schema id depending on type.
  #[inline]
  pub fn content_type(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RegionEntry::VT_CONTENT_TYPE, None)}
  }
  /// BLAKE3 of compressed plaintext before encryption (integrity).
  #[inline]
  pub fn payload_blake3(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(RegionEntry::VT_PAYLOAD_BLAKE3, None)}
  }
}

impl flatbuffers::Verifiable for RegionEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<RegionType>("type_", Self::VT_TYPE_, false)?
     .visit_field::<u64>("offset", Self::VT_OFFSET, false)?
     .visit_field::<u64>("length", Self::VT_LENGTH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<u32>("ordinal", Self::VT_ORDINAL, false)?
     .visit_field::<CompressionCodec>("compression", Self::VT_COMPRESSION, false)?
     .visit_field::<StorageMode>("storage", Self::VT_STORAGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ChunkRef>>>>("chunks", Self::VT_CHUNKS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<EncryptionInfo>>("encryption", Self::VT_ENCRYPTION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("content_type", Self::VT_CONTENT_TYPE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("payload_blake3", Self::VT_PAYLOAD_BLAKE3, false)?
     .finish();
    Ok(())
  }
}
pub struct RegionEntryArgs<'a> {
    pub type_: RegionType,
    pub offset: u64,
    pub length: u64,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ordinal: u32,
    pub compression: CompressionCodec,
    pub storage: StorageMode,
    pub chunks: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChunkRef<'a>>>>>,
    pub encryption: Option<flatbuffers::WIPOffset<EncryptionInfo<'a>>>,
    pub content_type: Option<flatbuffers::WIPOffset<&'a str>>,
    pub payload_blake3: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for RegionEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    RegionEntryArgs {
      type_: RegionType::Raw,
      offset: 0,
      length: 0,
      name: None,
      ordinal: 0,
      compression: CompressionCodec::None,
      storage: StorageMode::Inline,
      chunks: None,
      encryption: None,
      content_type: None,
      payload_blake3: None,
    }
  }
}

pub struct RegionEntryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RegionEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_type_(&mut self, type_: RegionType) {
    self.fbb_.push_slot::<RegionType>(RegionEntry::VT_TYPE_, type_, RegionType::Raw);
  }
  #[inline]
  pub fn add_offset(&mut self, offset: u64) {
    self.fbb_.push_slot::<u64>(RegionEntry::VT_OFFSET, offset, 0);
  }
  #[inline]
  pub fn add_length(&mut self, length: u64) {
    self.fbb_.push_slot::<u64>(RegionEntry::VT_LENGTH, length, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegionEntry::VT_NAME, name);
  }
  #[inline]
  pub fn add_ordinal(&mut self, ordinal: u32) {
    self.fbb_.push_slot::<u32>(RegionEntry::VT_ORDINAL, ordinal, 0);
  }
  #[inline]
  pub fn add_compression(&mut self, compression: CompressionCodec) {
    self.fbb_.push_slot::<CompressionCodec>(RegionEntry::VT_COMPRESSION, compression, CompressionCodec::None);
  }
  #[inline]
  pub fn add_storage(&mut self, storage: StorageMode) {
    self.fbb_.push_slot::<StorageMode>(RegionEntry::VT_STORAGE, storage, StorageMode::Inline);
  }
  #[inline]
  pub fn add_chunks(&mut self, chunks: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ChunkRef<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegionEntry::VT_CHUNKS, chunks);
  }
  #[inline]
  pub fn add_encryption(&mut self, encryption: flatbuffers::WIPOffset<EncryptionInfo<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<EncryptionInfo>>(RegionEntry::VT_ENCRYPTION, encryption);
  }
  #[inline]
  pub fn add_content_type(&mut self, content_type: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegionEntry::VT_CONTENT_TYPE, content_type);
  }
  #[inline]
  pub fn add_payload_blake3(&mut self, payload_blake3: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegionEntry::VT_PAYLOAD_BLAKE3, payload_blake3);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RegionEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RegionEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RegionEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RegionEntry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RegionEntry");
      ds.field("type_", &self.type_());
      ds.field("offset", &self.offset());
      ds.field("length", &self.length());
      ds.field("name", &self.name());
      ds.field("ordinal", &self.ordinal());
      ds.field("compression", &self.compression());
      ds.field("storage", &self.storage());
      ds.field("chunks", &self.chunks());
      ds.field("encryption", &self.encryption());
      ds.field("content_type", &self.content_type());
      ds.field("payload_blake3", &self.payload_blake3());
      ds.finish()
  }
}
pub enum TocOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Toc<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Toc<'a> {
  type Inner = Toc<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Toc<'a> {
  pub const VT_GENERATION: flatbuffers::VOffsetT = 4;
  pub const VT_PARENT_GENERATION: flatbuffers::VOffsetT = 6;
  pub const VT_FILE_UUID: flatbuffers::VOffsetT = 8;
  pub const VT_DEFAULT_STORAGE: flatbuffers::VOffsetT = 10;
  pub const VT_REGIONS: flatbuffers::VOffsetT = 12;
  pub const VT_ZSTD_DICT_BLAKE3: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Toc { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TocArgs<'args>
  ) -> flatbuffers::WIPOffset<Toc<'bldr>> {
    let mut builder = TocBuilder::new(_fbb);
    builder.add_parent_generation(args.parent_generation);
    builder.add_generation(args.generation);
    if let Some(x) = args.zstd_dict_blake3 { builder.add_zstd_dict_blake3(x); }
    if let Some(x) = args.regions { builder.add_regions(x); }
    if let Some(x) = args.file_uuid { builder.add_file_uuid(x); }
    builder.add_default_storage(args.default_storage);
    builder.finish()
  }


  /// Monotonic generation for this file_uuid lineage.
  #[inline]
  pub fn generation(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Toc::VT_GENERATION, Some(0)).unwrap()}
  }
  /// Parent generation (0 if genesis).
  #[inline]
  pub fn parent_generation(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Toc::VT_PARENT_GENERATION, Some(0)).unwrap()}
  }
  /// Echo of header file UUID.
  #[inline]
  pub fn file_uuid(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Toc::VT_FILE_UUID, None)}
  }
  /// sealed vs linked default for regions that omit storage.
  #[inline]
  pub fn default_storage(&self) -> StorageMode {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<StorageMode>(Toc::VT_DEFAULT_STORAGE, Some(StorageMode::Inline)).unwrap()}
  }
  #[inline]
  pub fn regions(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RegionEntry<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RegionEntry>>>>(Toc::VT_REGIONS, None)}
  }
  /// Optional zstd dictionary id (hash) used by text regions in this library.
  #[inline]
  pub fn zstd_dict_blake3(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Toc::VT_ZSTD_DICT_BLAKE3, None)}
  }
}

impl flatbuffers::Verifiable for Toc<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("generation", Self::VT_GENERATION, false)?
     .visit_field::<u64>("parent_generation", Self::VT_PARENT_GENERATION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("file_uuid", Self::VT_FILE_UUID, false)?
     .visit_field::<StorageMode>("default_storage", Self::VT_DEFAULT_STORAGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<RegionEntry>>>>("regions", Self::VT_REGIONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("zstd_dict_blake3", Self::VT_ZSTD_DICT_BLAKE3, false)?
     .finish();
    Ok(())
  }
}
pub struct TocArgs<'a> {
    pub generation: u64,
    pub parent_generation: u64,
    pub file_uuid: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub default_storage: StorageMode,
    pub regions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RegionEntry<'a>>>>>,
    pub zstd_dict_blake3: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for TocArgs<'a> {
  #[inline]
  fn default() -> Self {
    TocArgs {
      generation: 0,
      parent_generation: 0,
      file_uuid: None,
      default_storage: StorageMode::Inline,
      regions: None,
      zstd_dict_blake3: None,
    }
  }
}

pub struct TocBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TocBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_generation(&mut self, generation: u64) {
    self.fbb_.push_slot::<u64>(Toc::VT_GENERATION, generation, 0);
  }
  #[inline]
  pub fn add_parent_generation(&mut self, parent_generation: u64) {
    self.fbb_.push_slot::<u64>(Toc::VT_PARENT_GENERATION, parent_generation, 0);
  }
  #[inline]
  pub fn add_file_uuid(&mut self, file_uuid: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Toc::VT_FILE_UUID, file_uuid);
  }
  #[inline]
  pub fn add_default_storage(&mut self, default_storage: StorageMode) {
    self.fbb_.push_slot::<StorageMode>(Toc::VT_DEFAULT_STORAGE, default_storage, StorageMode::Inline);
  }
  #[inline]
  pub fn add_regions(&mut self, regions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<RegionEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Toc::VT_REGIONS, regions);
  }
  #[inline]
  pub fn add_zstd_dict_blake3(&mut self, zstd_dict_blake3: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Toc::VT_ZSTD_DICT_BLAKE3, zstd_dict_blake3);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TocBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TocBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Toc<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Toc<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Toc");
      ds.field("generation", &self.generation());
      ds.field("parent_generation", &self.parent_generation());
      ds.field("file_uuid", &self.file_uuid());
      ds.field("default_storage", &self.default_storage());
      ds.field("regions", &self.regions());
      ds.field("zstd_dict_blake3", &self.zstd_dict_blake3());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Toc`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_toc_unchecked`.
pub fn root_as_toc(buf: &[u8]) -> Result<Toc, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Toc>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Toc` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_toc_unchecked`.
pub fn size_prefixed_root_as_toc(buf: &[u8]) -> Result<Toc, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Toc>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Toc` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_toc_unchecked`.
pub fn root_as_toc_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Toc<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Toc<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Toc` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_toc_unchecked`.
pub fn size_prefixed_root_as_toc_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Toc<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Toc<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Toc and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Toc`.
pub unsafe fn root_as_toc_unchecked(buf: &[u8]) -> Toc {
  flatbuffers::root_unchecked::<Toc>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Toc and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Toc`.
pub unsafe fn size_prefixed_root_as_toc_unchecked(buf: &[u8]) -> Toc {
  flatbuffers::size_prefixed_root_unchecked::<Toc>(buf)
}
#[inline]
pub fn finish_toc_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Toc<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_toc_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Toc<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod format
}  // pub mod orchid

