//! Dart/Flutter lockfile extractor.
//!
//! Package names are indexed. Versions and sha256 checksums are not.
//! Dispatch lives in [`super::Extractor::extract`].

use crate::extractors::text::MAX_CONTENT_BYTES;

pub(crate) fn is_pubspec_lock_name(name: &str) -> bool {
    name.eq_ignore_ascii_case("pubspec.lock")
}

pub(crate) fn pubspec_lock_text(input: &str) -> String {
    let mut out = String::new();
    let mut in_packages = false;
    for raw in input.lines() {
        let trimmed = raw.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let indent = raw.chars().take_while(|ch| ch.is_whitespace()).count();
        if indent == 0 {
            in_packages = trimmed == "packages:";
            continue;
        }
        if in_packages && indent == 2 {
            if let Some(name) = trimmed.strip_suffix(':') {
                if !name.is_empty() && !name.contains(char::is_whitespace) {
                    push_line(&mut out, name);
                }
            }
        }
    }
    out.trim().to_string()
}

fn push_line(out: &mut String, value: &str) {
    let value = value.trim();
    if value.is_empty() || out.len() >= MAX_CONTENT_BYTES {
        return;
    }
    if !out.is_empty() {
        out.push('\n');
    }
    let room = MAX_CONTENT_BYTES.saturating_sub(out.len());
    out.push_str(&value.chars().take(room).collect::<String>());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn indexes_package_names_and_skips_checksums() {
        let text = pubspec_lock_text(
            r#"
# Generated by pub
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: SECRET
      url: "https://pub.dev"
    version: "1.18.0"
  orchid:
    dependency: "direct main"
    description:
      name: orchid
      sha256: OTHER
    version: "1.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
"#,
        );
        assert!(text.contains("collection"), "{text}");
        assert!(text.contains("orchid"), "{text}");
        assert!(!text.contains("SECRET"), "{text}");
        assert!(!text.contains("OTHER"), "{text}");
        assert!(!text.contains("1.18.0"), "{text}");
        assert!(!text.contains("3.0.0"), "{text}");
        assert!(is_pubspec_lock_name("pubspec.lock"));
        assert!(!is_pubspec_lock_name("pubspec.yaml"));
    }
}
