export global NavigationGlobal {
    in property <bool> workspace-panel-visible;
    in property <bool> notification-center-visible;
    in property <bool> dock-visible;
    in property <bool> hint-mode-enabled;
    in property <string> workspace-panel-title;
    in property <string> notification-center-title;
    in property <string> notification-center-placeholder;
    in property <string> panel-dismiss-label;
    in property <string> hint-dock-label;
    in property <string> hint-workspace-label;
    in property <string> hint-gestures-label;
}
