export global Strings {
    in property <string> window-title;
    in property <string> welcome;
    in property <string> subtitle;
    in property <string> version-label;
    in property <string> theme-label;
    in property <string> language-label;
    in property <string> density-label;
    in property <string> get-started-label;
    in property <string> workspace-new-label;
    in property <string> dock-add-label;
    in property <string> widget-close-tooltip;
}
